"""empty message

Revision ID: 705bcf8fc120
Revises: 
Create Date: 2017-02-19 13:19:18.969445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705bcf8fc120'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'recipe_author_fkey', 'recipe', type_='foreignkey')
    op.create_foreign_key(None, 'recipe', 'user', ['author'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.create_foreign_key(u'recipe_author_fkey', 'recipe', 'user', ['author'], ['id'])
    ### end Alembic commands ###
