"""empty message

Revision ID: 87749e03325d
Revises: 705bcf8fc120
Create Date: 2017-02-19 13:29:05.019144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87749e03325d'
down_revision = '705bcf8fc120'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Recipe_ingredients_rec_id_fkey', 'Recipe_ingredients', type_='foreignkey')
    op.drop_constraint(u'Recipe_ingredients_ingredient_id_fkey', 'Recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'Recipe_ingredients', 'recipe', ['rec_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'Recipe_ingredients', 'ingredient', ['ingredient_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Recipe_ingredients', type_='foreignkey')
    op.drop_constraint(None, 'Recipe_ingredients', type_='foreignkey')
    op.create_foreign_key(u'Recipe_ingredients_ingredient_id_fkey', 'Recipe_ingredients', 'ingredient', ['ingredient_id'], ['id'])
    op.create_foreign_key(u'Recipe_ingredients_rec_id_fkey', 'Recipe_ingredients', 'recipe', ['rec_id'], ['id'])
    ### end Alembic commands ###
